<a href="https://colab.research.google.com/github/PreranaRaoAdyapady1910/Machine-Learning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array([10,20,30,40])
print(a)

b=np.arange(1,11)
print(b)

c=np.linspace(0,100,5)
print(c)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[  0.  25.  50.  75. 100.]


In [ ]:
#Activity 2: Matrix operation
A = np.array(([1,2],[3,4]))
B = np.array(([5,6],[7,8]))
print(A+B)
print(A-B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
#Activity 3: Statistics
marks = np.array([75,90,60,88,30])
print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))
print(np.std(marks))

68.6
30
90
22.08710030764564


In [ ]:
#take weather data of past 1 month of udupi,
#1.find which is the hottest day and coldest day
#2.Calculate the avg temperature of overall month
#3. find which all days has above 35 deg celsius
import pandas as pd
df = pd.read_excel("weather.xlsx")
hottest = df.loc[df["Temperature"].idxmax()]
coldest = df.loc[df["Temperature"].idxmin()]
print("Hottest Day:")
print("Date:", hottest["Date"])
print("Temperature:", hottest["Temperature"], "°C")
print("\nColdest Day:")
print("Date:", coldest["Date"])
print("Temperature:", coldest["Temperature"], "°C")
average_temperature = df["Temperature"].mean()
print("\nAverage Temperature:")
print(round(average_temperature, 2), "°C")
above_35 = df[df["Temperature"] > 35]
print("\nDays above 35°C:")
if above_35.empty:
    print("No days had temperature above 35°C.")
else:
    print(above_35[["Date", "Temperature"]])

Hottest Day:
Date: 2026-07-09 00:00:00
Temperature: 28.5 °C

Coldest Day:
Date: 2026-07-01 00:00:00
Temperature: 24.5 °C

Average Temperature:
26.63 °C

Days above 35°C:
No days had temperature above 35°C.


In [ ]:
#pandas
import pandas as pd
student = {
    "Name":["A","B","C","D"],
     "Age":[23,30,60,12],
     "Marks":[98,66,85,60]
}
df = pd.DataFrame(student)
df

,Name,Age,Marks
0,A,23,98
1,B,30,66
2,C,60,85
3,D,12,60


In [ ]:
#Reading dataset
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)

df = iris.frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [ ]:
#Basic operations
df.info()
df.describe()
df.shape
df.columns
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2


In [ ]:
df[['sepal length (cm)', 'target']]
df.iloc[:5]
df.loc[10:20]


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0


In [ ]:
df[df['target']==1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1


In [ ]:
df.sort_values(by='sepal length (cm)')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2


In [ ]:
#assignment-2
#Use titanic dataset to
#1.find total no of passengers
#2.find avg age of survivors and non survivors
#3.list the passengers who are older than 60 years
#4. find the avg fair for each p[assenger class
import pandas as pd
df = pd.read_csv('/content/Titanic-Dataset.csv')
total_passengers = len(df)
print("Total number of passengers are:", total_passengers)
avg_age = df.groupby('Survived')['Age'].mean()
print("\nAverage age of survivors:", avg_age[1])
print("Average age of non-survivors:", avg_age[0])
older_passengers = df[df['Age'] > 60]
print("\nPassengers older than 60 years:")
print(older_passengers)
avg_fare = df.groupby('Pclass')['Fare'].mean()
print("\nAverage fare for each passenger class:")
print(avg_fare)

Total number of passengers are: 891

Average age of survivors: 28.343689655172415
Average age of non-survivors: 30.62617924528302

Passengers older than 60 years:
     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0 